package logger;

import event.Event;
import eventHistory.EventHistory;

import java.util.Map;

/**
 * An interface that represents a logger of events generated by an agent.
 */
public interface EventLogger {

    /**
     * Published an event with the given agent name and event information.
     * @param agentName the name of the agent
     * @param event the event to be published
     */
    void publishEvent(String agentName, Event event);

    /**
     * Returns the history of events.
     * @return the event history
     */
    Map<String, EventHistory> getHistory();

    /**
     * Saves the single agent log in file.
     * @param agentName the name of the agent to save
     */
    void saveAgentLogInFile(String agentName);

    /**
     * Saves the single agent log as json in file.
     * @param agentName the name of the agent to save
     */
    void saveAgentLogAsJson(String agentName);

    /**
     * Saves the log in file specified by the given file name.
     * @param fileName the name of the file to save the log
     */
    void saveLogInFile(String fileName);

    /**
     * Saves the log as json in file specified by the given file name.
     * @param fileName the name of the file to save the log
     */
    void saveLogAsJson(String fileName);
}
