package logger;

import event.Event;

/**
 * An interface that represents a logger of events generated by an agent.
 */
public interface Logger {

    /**
     * Published an event with the given agent name and event information.
     * @param agentName the name of the agent
     * @param event the event to be published
     */
    void publishEvent(String agentName, Event event);

    /**
     * Saves the log in file specified by the given file name.
     * @param fileName the name of the file to save the log
     */
    void saveLogInFile(String fileName);
}
