package event;

/**
 * An interface that represents a common event generated by an agent.
 */
public interface Event {

    /**
     * Returns the timestamp at which the event occurred.
     * @return the timestamp of the event
     */
    long getTimestamp();

}